### ISSUE TITLE
urllib3 exceptions

### ISSUE THREAD

**Issue by edrahn** [kennethreitz/requests#2410]
Traceback (most recent call last):
  File "./dlcharts.py", line 111, in <module>
    content = get_url(url)
  File "/home/ed/projects/equalog/src/web.py", line 118, in get_url
    referrer=referrer)
  File "/home/ed/projects/equalog/src/web.py", line 81, in get_content
    content = response.content
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 694, in content
    self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 627, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 242, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python2.7/dist-packages/urllib3/response.py", line 200, in read
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='....', port=80): Read timed out.

**Comment by Lukasa** [comment]
What version of requests are you using? This should have been patched in 2.4.0.

**Comment by edrahn** [comment]
I'm not sure what version it was. I was using the system package instead of my virtaulenv one, and that fixed it. Most likey diferent versions.
