### ISSUE TITLE
ConnectionError and socket.gaierror occurred on IPv6-enabled system

### ISSUE THREAD

**Issue by shichao-an** [kennethreitz/requests#2521]
I tried to make a request with a tool that uses python-requests on a Ubuntu 14.04 server with IPv6 enabled (with inet6 interface configured at `/etc/network/interfaces`) and encountered the following errors:

```bash
$ 115down 
Traceback (most recent call last):
  File "/usr/local/bin/115down", line 130, in <module>
    main()
  File "/usr/local/bin/115down", line 126, in main
    args.sub_num, args.count, args.sub_count, args.tasks)
  File "/usr/local/bin/115down", line 64, in get_entries
    api.login(username, password, section)
  File "/usr/local/lib/python2.7/dist-packages/u115/api.py", line 248, in login
    if self.has_logged_in:
  File "/usr/local/lib/python2.7/dist-packages/u115/api.py", line 297, in has_logged_in
    r = self.http.get(CHECKPOINT_URL)
  File "/usr/local/lib/python2.7/dist-packages/u115/api.py", line 56, in get
    r = self.session.get(url, params=params)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 467, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 455, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 558, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 378, in send
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='passport.115.com', port=80): Max retries exceeded with url: /?ct=ajax&ac=ajax_check_point (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)
Exception requests.exceptions.ConnectionError: ConnectionError(MaxRetryError("HTTPConnectionPool(host='passport.115.com', port=80): Max retries exceeded with url: /?ct=ajax&ac=ajax_check_point (Caused by <class 'socket.gaierror'>: [Errno -2] Name or service not known)",),) in <bound method API.__del__ of <u115.api.API object at 0x7fe060092210>> ignored
```

When disabled IPv6 by commenting relevant lines in `/etc/network/interfaces` and reboot, everything works. 

Anyone have any ideas?

**Comment by Lukasa** [comment]
`socket.gaierror` seems to suggest that you're failing a DNS lookup. Try this:

``` python
import socket
socket.getaddrinfo('passport.115.com', 80)
```

in both IPv6 and IPv4 mode, and see if the problem reproduces.

**Comment by shichao-an** [comment]
To reproduce,

```
>>> import socket
>>> socket.getaddrinfo('passport.115.com', 80)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno -2] Name or service not known
```

But I think I got the cause, when I tried to disable IPv6 editing the default `/etc/network/interfaces`, I found DNS is set only for IPv6 of the eth0 interface but not for IPv4:

```
dns-nameservers 2001:4860:4860::8844 2001:4860:4860::8888 8.8.8.8
```

So I manually added 8.8.8.8 and 8.8.4.4 to IPv4 and it worked.

It seems the default system is not "properly" configured for this scenario

**Comment by Lukasa** [comment]
I'm glad you were able to diagnose the problem!
