### ISSUE TITLE
TypeError: __str__ returned non-string (type Error)

### ISSUE THREAD

**Issue by mktums** [kennethreitz/requests#2524]
OS X 10.9
Python 2.7.9

```
$ pip freeze
cffi==0.9.2
cryptography==0.8.1
enum34==1.0.4
gitdb==0.6.4
GitPython==0.3.6
ndg-httpsclient==0.3.3
pyasn1==0.1.7
pycparser==2.10
pyOpenSSL==0.14
requests==2.6.0
requests-toolbelt==0.3.1
six==1.9.0
smmap==0.9.0
``` 

On request to website with TLS 1.0 `https://codeforge.lbl.gov/frs/download.php/409/fastbit-ibis1.3.8.tar.gz` I'm getting:

```python
Traceback (most recent call last):
  File "./main.py", line 118, in <module>
    resp = downloader.run()
  File "/Users/mktums/Projects/brew404/downloaders.py", line 64, in run
    resp = self.fetch()
  File "/Users/mktums/Projects/brew404/downloaders.py", line 59, in fetch
    resp = s.send(req, verify=verify_ssl, allow_redirects=True, timeout=20)
  File "/Users/mktums/.virtualenvs/brew/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/mktums/.virtualenvs/brew/lib/python2.7/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/Users/mktums/.virtualenvs/brew/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/Users/mktums/.virtualenvs/brew/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 344, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/Users/mktums/.virtualenvs/brew/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 314, in _raise_timeout
    if 'timed out' in str(err) or 'did not complete (read)' in str(err):  # Python 2.6
TypeError: __str__ returned non-string (type Error)
```

**Comment by Lukasa** [comment]
Thanks for reporting this! This is currently tracked under shazow/urllib3#556, so I'm going to close this issue to centralise discussion there.

**Comment by mktums** [comment]
@Lukasa Thanks for fast reply!

**Comment by gdonzy** [comment]
how to fix this bug? any ideas?

**Comment by Lukasa** [comment]
@gdonzy Please read the above issue, which links to a related tracking issue.

**Comment by gdonzy** [comment]
Thanks a lot. When I use "requests.get("xxxx", verify=False)", the bug is fixed.

**Comment by arvindsree** [comment]
Can I re open this? I am getting this even for a signed certificate.  I cannot use verify = False

**Comment by Lukasa** [comment]
No, this was fixed a long time ago. You should update instead.
