### ISSUE TITLE
UnicodeDecodeError when post a local image file

### ISSUE THREAD

**Issue by shelper** [kennethreitz/requests#2607]
i am using python 3.4, and request 2.7
i am trying to post a local jpg image like this, and got encoding error:

        import requests
        response = requests.post("url here",
          params={
            "image": open("path to local image", mode="r")
          }
        )

if i change the mode to 'rb' the error is gone:

        import requests
        response = requests.post("url here",
          params={
            "image": open("path to local image", mode="rb")
          }
        )

the error details are listed below:
'Traceback (most recent call last):
  File "test_facemark.py", line 7, in <module>
    "image": open("path to the jpg file", mode="r")
  File "c:\python34\lib\site-packages\requests\api.py", line 109, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "c:\python34\lib\site-packages\requests\api.py", line 50, in reques    response = session.request(method=method, url=url, **kwargs)
  File "c:\python34\lib\site-packages\requests\sessions.py", line 451, in
t
    prep = self.prepare_request(req)
  File "c:\python34\lib\site-packages\requests\sessions.py", line 382, in
e_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "c:\python34\lib\site-packages\requests\models.py", line 304, in pr    self.prepare_url(url, params)
  File "c:\python34\lib\site-packages\requests\models.py", line 397, in prurl
    enc_params = self._encode_params(params)
  File "c:\python34\lib\site-packages\requests\models.py", line 92, in _enarams
    for v in vs:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xff in position 0: illeltibyte sequence'

**Comment by Lukasa** [comment]
In Python 3, if you open a file in `'r'` mode, that will open the file in _text_ mode. This means that Python will attempt to use your system encoding to decode the bytes in the file. That is causing this exception here.

When uploading binary data to the web, you should always open the file in bytes mode: `'rb'`. You _should_ also do that with text files, really, to avoid problems with an encoding round trip.
