### ISSUE TITLE
Requests does not support encoding headers to ascii?

### ISSUE THREAD

**Issue by zhaoguixu** [kennethreitz/requests#2637]
A simple test case:
```python    
request = requests.Request(method='GET', url='https://httpbin.org/get')
request.headers = {u'referer': u'http://xx.com?x=føø'}
prepared = request.prepare()
requests.Session().send(prepared)
```

```
Traceback (most recent call last):
  ...
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 566, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 331, in send
    timeout=timeout
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 558, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 383, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 975, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1008, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python2.7/httplib.py", line 955, in putheader
    hdr = '%s: %s' % (header, '\r\n\t'.join([str(v) for v in values]))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 17-18: ordinal not in range(128)
```

**Comment by Lukasa** [comment]
Requests does not encode header values for you because we don't know what encoding you want to send. You'll need to pick an encoding for the header value yourself and encode it.
