### ISSUE TITLE
Address family not supported by protocol

### ISSUE THREAD

**Issue by Johnathon332** [kennethreitz/requests#2694]
I am getting the error when making a request to my web api hosted on another machine on IIS express, this is in order for me to debug my application, however when I run my python code I get the error 

requests.exceptions.ConnectionError: ('Connection aborted.', error(97, 'Address family not supported by protocol'))

Here is the traceback:

Traceback (most recent call last):
  File "Allocator.py", line 201, in <module>
    Main()
  File "Allocator.py", line 154, in Main
    requestResult = MakeRequest("")
  File "Allocator.py", line 36, in MakeRequest
    result = requests.get(constURLString + "?lastUpdate=" + urlParameters)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(97, 'Address family not supported by protocol'))

**Comment by sigmavirus24** [comment]
Closing to centralize discussion on [StackOverflow](https://stackoverflow.com/questions/31695430/address-family-not-supported-by-protocol-making-request-to-webapi) given there is more detail in the question than was provided in the bug report.
