### ISSUE TITLE
Extra commas in NO_PROXY or no_proxy env var break all proxy requests

### ISSUE THREAD

**Issue by tlc** [kennethreitz/requests#2720]
Using requests 2.7.0 via TwitterAPI, I successfully proxy requests by setting https_proxy in my environment.  If either `no_proxy` or `NO_PROXY` is set to `,` or `foo.com,,bar.com` or `foo.com,`, I get:
```
WARNING:root:<class 'requests.exceptions.ConnectTimeout'> HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/update.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f031cdf7908>, 'Connection to api.twitter.com timed out. (connect timeout=5)'))
ERROR:__main__:Tweet exception
Traceback (most recent call last):
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 134, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 88, in create_connection
    raise err
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/packages/urllib3/util/connection.py", line 78, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
    body=body, headers=headers)
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
    self._validate_conn(conn)
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
    conn.connect()
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 204, in connect
    conn = self._new_conn()
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/packages/urllib3/connection.py", line 139, in _new_conn
    (self.host, self.timeout))
requests.packages.urllib3.exceptions.ConnectTimeoutError: (<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f031cdf7908>, 'Connection to api.twitter.com timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/packages/urllib3/connectionpool.py", line 597, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/packages/urllib3/util/retry.py", line 271, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/update.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f031cdf7908>, 'Connection to api.twitter.com timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/TwitterAPI/TwitterAPI.py", line 121, in request
    proxies=self.proxies)
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/troy/BUDDIES/lib/python3.4/site-packages/requests/adapters.py", line 419, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/update.json (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f031cdf7908>, 'Connection to api.twitter.com timed out. (connect timeout=5)'))
```
which I believe indicates it was no longer trying to use the proxy.  
So I theorize an empty `no_proxy` environment variable *segment* defaults to `*`.

**Comment by Lukasa** [comment]
Yup, this looks like a legitimate bug: our parsing of the `no_proxy` environment variable does not tolerate spaces.

I think we can fix this up pretty easily.

**Comment by Lukasa** [comment]
This should be fixed by #2721.

**Comment by seema-kote** [comment]
Hey Guys, Here's quick solution for this PIP bug. simply Take HTTP_PROXY and HTTPS_PROXY env. vars and delete those from your system. Whenever you connect to proxy network, use the backed up HTTP_PROXY,HTTPS_PROXY vars.

**Comment by QGB** [comment]
@seema-kote   how to use  no_proxy bypass  every url
