### ISSUE TITLE
SSLError when use Pyinstaller

### ISSUE THREAD

**Issue by zotix** [kennethreitz/requests#2776]
I try to mix my python desktop app to exe file. When execute without compiler is OK but EXE it show error as below
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\try\build\main\out00-PYZ.pyz\Tkinter", line 1536, in __call__
  File "<string>", line 154, in on_btn_download
  File "C:\try\build\main\out00-PYZ.pyz\usgsDownloader", line 57, in search
  File "C:\try\build\main\out00-PYZ.pyz\usgs.api", line 302, in search
  File "C:\try\build\main\out00-PYZ.pyz\requests.api", line 109, in post
  File "C:\try\build\main\out00-PYZ.pyz\requests.api", line 50, in request
  File "C:\try\build\main\out00-PYZ.pyz\requests.sessions", line 465, in request
  File "C:\try\build\main\out00-PYZ.pyz\requests.sessions", line 573, in send
  File "C:\try\build\main\out00-PYZ.pyz\requests.adapters", line 431, in send
SSLError: [Errno 2] No such file or directory
```

Compile command
```
C:\try>pyinstaller -F --hidden-import=requests main.py
```

What should I fix it? thank

**Comment by sigmavirus24** [comment]
This is not a bug in requests. This is a bug in PyInstaller since it doesn't know how to detect static package data (e.g., the certificate bundle that requests is packaged with).

**Comment by zotix** [comment]
Thanks sigmavirus24 for giving a hint.

Fix this by http://stackoverflow.com/questions/21201238/twilio-python-module-errors-after-compiling/21206079#21206079

**Comment by hu7241** [comment]
I too have the trouble with Pyinstaller and Requests. Thanks folks for posting the question and for pointing us in the right direction, much appreciated!
