### ISSUE TITLE
ImportError: cannot import name certs

### ISSUE THREAD

**Issue by muhammad-ammar** [kennethreitz/requests#2780]
All the requests versions except `requests==0.14.2` giving me below exception. Any idea what might be wrong?

```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/edx/app/xqueue/xqueue/xqueue/wsgi.py", line 50, in get_response
    return super(ForceReadPostHandler, self).get_response(request)
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/xqueue/xqueue/xqueue/urls.py", line 4, in <module>
    url(r'^xqueue/', include('queue.urls')),
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/xqueue/xqueue/queue/urls.py", line 4, in <module>
    from . import ext_interface
  File "/edx/app/xqueue/xqueue/queue/ext_interface.py", line 7, in <module>
    import requests
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/requests/utils.py", line 24, in <module>
    from . import certs
ImportError: cannot import name certs
```

***requests==0.14.2*** gives this exception
```python
Traceback (most recent call last):
  File "/usr/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 218, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 264, in handle_uncaught_exception
    if resolver.urlconf_module is None:
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 396, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/xqueue/xqueue/xqueue/urls.py", line 4, in <module>
    url(r'^xqueue/', include('queue.urls')),
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 33, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/edx/app/xqueue/xqueue/queue/urls.py", line 4, in <module>
    from . import ext_interface
  File "/edx/app/xqueue/xqueue/queue/ext_interface.py", line 7, in <module>
    import requests
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from . import utils
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/requests/utils.py", line 22, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/requests/compat.py", line 95, in <module>
    from .packages import chardet
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/requests/packages/urllib3/__init__.py", line 16, in <module>
    from .connectionpool import (
  File "/edx/app/xqueue/venvdj18/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 22, in <module>
    from Queue import LifoQueue, Empty, Full
ImportError: cannot import name LifoQueue
```

**Comment by sigmavirus24** [comment]
> All the requests versions except requests==0.14.2 giving me below exception. Any idea what might be wrong?

Can you enumerate exactly which versions you've tried? The latest version would not match your first traceback. Further, how are you installing requests? You've given no information to help you out. I can presume you're trying to set up an edx development environment but provided nothing to help us reproduce.

**Comment by muhammad-ammar** [comment]
@sigmavirus24 As per my further debugging, the issue is not related to requests. I am closing this issue.
Thanks @sigmavirus24
