### ISSUE TITLE
pooled connections are not returned to the pool

### ISSUE THREAD

**Issue by sileht** [kennethreitz/requests#2784]
Hi

When pool_block=True on an HTTPAdapter is used and the connection fails 
this one seems not return to the pool.

To reproduce:

    # python
    >>> import requests
    >>> a = requests.adapters.HTTPAdapter(pool_maxsize=1, pool_block=True)
    >>> s = requests.Session()
    >>> s.mount("http://", a)
    >>> s.get("http://localhost:12345")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 477, in get
        return self.request('GET', url, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 413, in send
        raise ConnectionError(err, request=request)
    requests.exceptions.ConnectionError: ('Connection aborted.', error(111, 'Connection refused'))
    >>> s.get("http://localhost:12345")
    
    # here the session objects is stuck.

Cheers,

**Comment by sileht** [comment]
After deeper investigation it seems to be that one: https://github.com/shazow/urllib3/issues/659

**Comment by sileht** [comment]
Duplicate of kennethreitz/requests#2687
