### ISSUE TITLE
Failure in tests on specfic host

### ISSUE THREAD

**Issue by rickvanderzwet** [kennethreitz/requests#2787]
Hi I am facing a weird issue both with python2 and python3 which seems to be limited to a specific host (my laptop). A few of the test cases are failing and I do not know why.

```
[rvdzwet@rvdzwet-asus tmp]$ git clone https://github.com/kennethreitz/requests.git
Cloning into 'requests'...
remote: Counting objects: 15705, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 15705 (delta 0), reused 0 (delta 0), pack-reused 15701
Receiving objects: 100% (15705/15705), 6.52 MiB | 147.00 KiB/s, done.
Resolving deltas: 100% (8874/8874), done.
Checking connectivity... done.

[rvdzwet@rvdzwet-asus tmp]$ cd requests/

[rvdzwet@rvdzwet-asus requests]$ ls
AUTHORS.rst  docs  ext  HISTORY.rst  LICENSE  Makefile  MANIFEST.in  NOTICE  README.rst  requests  requirements.txt  setup.cfg  setup.py  test_requests.py
[rvdzwet@rvdzwet-asus requests]$ ./test_requests.py 
................FF.................................................................................................................................
======================================================================
FAIL: test_auth_is_retained_for_redirect_on_host (__main__.RequestsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_requests.py", line 1002, in test_auth_is_retained_for_redirect_on_host
    assert h1 == h2
AssertionError

======================================================================
FAIL: test_auth_is_stripped_on_redirect_off_host (__main__.RequestsTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_requests.py", line 995, in test_auth_is_stripped_on_redirect_off_host
    assert not r.request.headers.get('Authorization', '')
AssertionError

----------------------------------------------------------------------
Ran 147 tests in 33.126s

FAILED (failures=2)
```
Some details of the host:
```
[rvdzwet@rvdzwet-asus requests]$ lsb_release -a
LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	Fedora
Description:	Fedora release 21 (Twenty One)
Release:	21
Codename:	TwentyOne

[rvdzwet@rvdzwet-asus requests]$ python -V
Python 2.7.8

[rvdzwet@rvdzwet-asus requests]$ python3 -V
Python 3.4.1
```

**Comment by rixvet** [comment]
Found the culprit (after looking looking at the streams with wireshark). It was caused by a erroneous `~/.netrc` entry.

```
[rvdzwet@rvdzwet-asus requests]$ cat ~/.netrc 
default login anonymous password user@site
```

Removing this entry fixed my issue. Thanks to you folks for providing the extended test suite, allowing quick debugging!
