### ISSUE TITLE
test_connection_error_invalid_domain and test_connection_error_invalid_port fail with proxies

### ISSUE THREAD

**Issue by frispete** [kennethreitz/requests#2841]
testing should handle environments with proxies consciously, otherwise these tests fail:

``` ======================================================================
ERROR: test_connection_error_invalid_domain (__main__.RequestsTestCase)
Connecting to an unknown domain should raise a ConnectionError
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_requests.py", line 322, in test_connection_error_invalid_domain
    requests.get("http://doesnotexist.google.com")
  File "/usr/lib/python2.7/site-packages/_pytest/python.py", line 1307, in __exit__
    pytest.fail("DID NOT RAISE")
  File "/usr/lib/python2.7/site-packages/_pytest/runner.py", line 478, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE

======================================================================
ERROR: test_connection_error_invalid_port (__main__.RequestsTestCase)
Connecting to an invalid port should raise a ConnectionError
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_requests.py", line 327, in test_connection_error_invalid_port
    requests.get("http://httpbin.org:1", timeout=1)
  File "/usr/lib/python2.7/site-packages/_pytest/python.py", line 1307, in __exit__
    pytest.fail("DID NOT RAISE")
  File "/usr/lib/python2.7/site-packages/_pytest/runner.py", line 478, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: DID NOT RAISE
```

Environment: openSUSE 13.2/x86_64, squid 3 proxy

**Comment by Lukasa** [comment]
Yeah, this is probably true. I suspect we'll fix it by moving to an entirely offline test suite though.

**Comment by nateprewitt** [comment]
Neither of these tests exist anymore, so I think this can be closed out.
