### ISSUE TITLE
SSL error: bad handshake

### ISSUE THREAD

**Issue by Mohammed-Aadil** [kennethreitz/requests#2971]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dev-django1/.virtualenvs/logic_srv/local/lib/python2.7/site-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/home/dev-django1/.virtualenvs/logic_srv/local/lib/python2.7/site-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/dev-django1/.virtualenvs/logic_srv/local/lib/python2.7/site-packages/requests/sessions.py", line 464, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/dev-django1/.virtualenvs/logic_srv/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/home/dev-django1/.virtualenvs/logic_srv/local/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno bad handshake] [('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')]

I do not know why it is coming in requests 2.6.0 while it is not coming in requests==2.2.1. This problem start arising yesterday when I hit it to google api on link https://www.googleapis.com/oauth2/v1/tokeninfo. I can't use verify=False as many stackoverflow thread is advising. And I'm pretty sure I have used ssl certificate properly in my web site too.

**Comment by Lukasa** [comment]
What OS are you using?

**Comment by Mohammed-Aadil** [comment]
Yeah im using linux. Btw I fixed the error by removing and installing virtualenv package, not sure why this happened but i got it running. Thank you for your reply :)
