### ISSUE TITLE
Requests causing NoneType error

### ISSUE THREAD

**Issue by MNgeographer** [kennethreitz/requests#3062]
I've pip installed requests (requests-2.9.1-py2.py3-none-any).  I'm working on a script to download an excel file from my company's SharePoint onto my local drive using Python 2.7.  Even if I comment out every last bit of code other than "import requests" at the beginning, I get this error message:

_"AttributeError: 'NoneType' object has no attribute 'a2b_hex' "_

So something about importing the requests module is causing this problem. Here's the full traceback:

_Traceback (most recent call last): File "H:\PythonSandbox\GetSharePoint.py", line 1, in import requests

File "C:\Python27\ArcGIS10.1\lib\site-packages\requests__init__.py", line 58, in from . import utils

File "C:\Python27\ArcGIS10.1\lib\site-packages\requests\utils.py", line 26, in

from .compat import parse_http_list as _parse_list_header

File "C:\Python27\ArcGIS10.1\lib\site-packages\requests\compat.py", line 29, in

import json

File "C:\Python27\ArcGIS10.1\Lib\json__init__.py", line 108, in from .decoder import JSONDecoder

File "C:\Python27\ArcGIS10.1\Lib\json\decoder.py", line 24, in NaN, PosInf, NegInf = _floatconstants()

File "C:\Python27\ArcGIS10.1\Lib\json\decoder.py", line 18, in _floatconstants _BYTES = '7FF80000000000007FF0000000000000'.decode('hex')

File "C:\Python27\ArcGIS10.1\Lib\encodings\hex_codec.py", line 42, in hex_decode

output = binascii.a2b_hex(input)

AttributeError: 'NoneType' object has no attribute 'a2b_hex'

Failed to execute (GetSharePoint)._

Apologies if this isn't worded well, I'm a relative novice and new to github.  Thanks!

**Comment by Lukasa** [comment]
This looks like an error in your system. For some reason, the hex_codec module's import of binascii is broken: something is patching it away or otherwise messing with it such that it doesn't not function correctly.

Taking you through debugging that is not really something that we can do here (this is a requests bug tracker, and the issue here is not with requests), but nonetheless, you should be investigating why binascii is not functioning well here. Given that this is in the standard library and that your code apparently _only_ imports requests, either ArcGIS have busted something or your system is pretty remarkably borked.

FWIW, you should be able to reproduce this error by using just the following script:

``` python
import json
```

That involves no third-party code, which should demonstrate that the problem is not in requests. =)
