### ISSUE TITLE
Be able to set _MAXHEADERS in httplib.py

### ISSUE THREAD

**Issue by sloh** [kennethreitz/requests#3097]
I am making a GET request which returns a response with 100+ headers because I am printing debug statements in it, so when I use requests to get the URL, I am a similar error like below:

Traceback (most recent call last):
  File "......", line ....., in get_response
    response = requests.get(url)
  File "/Users/loh/myvirtualenvs/auto_ssai2.7/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/Users/loh/myvirtualenvs/auto_ssai2.7/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/loh/myvirtualenvs/auto_ssai2.7/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/loh/myvirtualenvs/auto_ssai2.7/lib/python2.7/site-packages/requests/adapters.py", line 426, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', HTTPException('got more than 100 headers',))

Need a way to change _MAXHEADERS in httplib.py as suggested here:
http://stackoverflow.com/questions/23055378/http-client-httpexception-got-more-than-100-headers

**Comment by sigmavirus24** [comment]
I'm sorry. I don't understand. Does something like

``` py
import httplib  # or http.client if you're on Python 3

httplib._MAXHEADERS = 1000
```

Not work for you? Given that this seems to be exceptionally rare, I'm not sure we need a way to do this (or override this).
