### ISSUE TITLE
unhandled exception on timeout

### ISSUE THREAD

**Issue by alanhamlett** [kennethreitz/requests#3217]
```python
Traceback (most recent call last):
  File "requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "requests/packages/urllib3/util/retry.py", line 285, in increment
    _observed_errors=_observed_errors)
  File "requests/packages/urllib3/util/retry.py", line 151, in new
    raise_on_status=self.raise_on_status,
AttributeError: 'Retry' object has no attribute 'raise_on_status'
```

You can reproduce this by changing line 140 of `requests/packages/urllib3/connection.py` to:
```
140         try:
141             raise SocketTimeout('')
142             conn = connection.create_connection(
143                 (self.host, self.port), self.timeout, **extra_kw)
144
145         except SocketTimeout as e:
```

This forces a `SocketTimeout` and causes the unhandled exception when calling `Retry.new`.

**Comment by Lukasa** [comment]
Hey @alanhamlett, thanks for reporting this!

This will be fixed when we release the next minor version of requests, which will bring in an updated version of urllib3.
