### ISSUE TITLE
requests throws an exception when using future strings on Py2

### ISSUE THREAD

**Issue by st-pasha** [kennethreitz/requests#3400]
We are using `future` module in our project ([http://python-future.org/](http://python-future.org/)), and it appears that `requests` has trouble processing futurized strings in Python 2.7.12.

Test case:
```
from future.types import newstr as str
from requests import get
get("http://google.com/search", params={"q": str("/foo/bar")})
```
This throws an exception "KeyError: 47".

**Comment by kennethreitz** [comment]
- I have never heard of python-future before.
- It has incomplete API documentation, specifically none around `newstr`.

**Comment by sigmavirus24** [comment]
I made a virtual environment to reproduce this and it's absolutley reproducible... except that the exception comes from _the standard library_.

All that's necessary to reproduce this is:

``` py
>>> import urllib
>>> urllib.urlencode({'q': str('/foo')}, doseq=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1359, in urlencode
    v = quote_plus(v.encode("ASCII","replace"))
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1310, in quote_plus
    return quote(s, safe)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1303, in quote
    return ''.join(map(quoter, s))
KeyError: 47
```

This is entirely the fault of `future.types.newstr.newstr`.

If you do not use `future.types.newstr` then instead you get:

``` py
>>> urllib.urlencode({'q': '/foo'}, doseq=True)
'q=%2Ffoo'
```

This is a bug in future.
