### ISSUE TITLE
SSLError: EOF occurred in violation of protocol (_ssl.c:590)

### ISSUE THREAD

**Issue by JonahCun** [kennethreitz/requests#3431]
Hi Guys,

I was using the maps absolutely fine last night.

anyway this morning when I wake up I get this error?
The problems start when the debugger pin code is shown..

any ideas how to get around this?

Thanks 

Jonah

 * Debugger pin code: 315-030-935
Exception in thread search_thread:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "example.py", line 581, in main
    api_endpoint, access_token, profile_response = login(args)
  File "example.py", line 92, in memoizer
    cache[key] = obj(*args, **kwargs)
  File "example.py", line 514, in login
    access_token = get_token(args.auth_service, args.username, global_password)
  File "example.py", line 429, in get_token
    global_token = login_ptc(username, password)
  File "example.py", line 331, in login_ptc
    r = SESSION.get(LOGIN_URL, headers=head)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:590)

**Comment by RomGutman** [comment]
Facing the same problem
