### ISSUE TITLE
Secure proxies are not supported

### ISSUE THREAD

**Issue by dessant** [kennethreitz/requests#3468]
Requests using [secure web proxies](https://www.chromium.org/developers/design-documents/secure-web-proxy) are failing. You can fetch a new proxy and credentials with [oprah-proxy](https://github.com/spaze/oprah-proxy) for testing.

```python
import requests


proxy = '107.182.238.96'
port = 8181
user = ''
passw = ''

proxies = {
    'https': 'https://{}:{}@{}:{}/'.format(user, passw, proxy, port),
}

requests.get('https://httpbin.org/get', proxies=proxies)
```

```python
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 572, in urlopen
    self._prepare_proxy(conn)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 780, in _prepare_proxy
    conn.connect()
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 267, in connect
    self._tunnel()
  File "C:\Python34\lib\http\client.py", line 852, in _tunnel
    (version, code, message) = response._read_status()
  File "C:\Python34\lib\http\client.py", line 368, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 403, in send
    timeout=timeout
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\util\retry.py", line 255, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\packages\six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 572, in urlopen
    self._prepare_proxy(conn)
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 780, in _prepare_proxy
    conn.connect()
  File "C:\Python34\lib\site-packages\requests\packages\urllib3\connection.py", line 267, in connect
    self._tunnel()
  File "C:\Python34\lib\http\client.py", line 852, in _tunnel
    (version, code, message) = response._read_status()
  File "C:\Python34\lib\http\client.py", line 368, in _read_status
    raise BadStatusLine(line)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\x16',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\test.py", line 13, in <module>
    requests.get('https://httpbin.org/get', proxies=proxies)
  File "C:\Python34\lib\site-packages\requests\api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python34\lib\site-packages\requests\api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python34\lib\site-packages\requests\sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python34\lib\site-packages\requests\adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('\x15\x03\x01\x00\x02\x02\x16',))
```

**Comment by Lukasa** [comment]
Requests does not support secure web proxies at this time, I'm afraid, and there is no plan to do so in the immediate future.
