### ISSUE TITLE
Error received after updating the requests package

### ISSUE THREAD

**Issue by MehmetAzizYirik** [kennethreitz/requests#3548]
@shazow @Lukasa @mcescalante @borbamartin

Hi guys;

I just tried to extract data by using the URL of the webservices; moreover, I used the requests package however it returned the error "TypeError: __str__ returned non-string (type SysCallError)" according to that; I just read the section for the issue at GitHub and upgraded the requests package. However, it returned another error. Before updating the code worked for an hour and stopped and gave the error as I shared "TypeError: __str__ returned non-string (type SysCallError)" however right now it does not work; moreover jit just returns the traceback:

Traceback (most recent call last):
  File "C:\Users\may\Desktop\Documents\BOUN-CSE\Master Thesis\Project Code Files\pubchem\PubchemMapping.py", line 35, in <module>
    activities = new_client.activity.filter(target_chembl_id__in=[target['target_chembl_id'] for target in targets])
  File "C:\Python27\lib\site-packages\chembl_webresource_client\query_set.py", line 114, in next
    self.chunk = self.query.get_page()
  File "C:\Python27\lib\site-packages\chembl_webresource_client\url_query.py", line 390, in get_page
    res = session.post(self.base_url + '.' + self.frmt, data=data, timeout=self.timeout)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Python27\lib\site-packages\requests_cache\core.py", line 126, in request
    **kwargs
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests_cache\core.py", line 97, in send
    response, timestamp = self.cache.get_response_and_time(cache_key)
  File "C:\Python27\lib\site-packages\requests_cache\backends\base.py", line 70, in get_response_and_time
    if key not in self.responses:
  File "C:\Python27\lib\_abcoll.py", line 388, in __contains__
    self[key]
  File "C:\Python27\lib\site-packages\requests_cache\backends\storage\dbdict.py", line 163, in __getitem__
    return pickle.loads(bytes(super(DbPickleDict, self).__getitem__(key)))
  File "C:\Python27\lib\copy_reg.py", line 50, in _reconstructor
    obj = base.__new__(cls, state)
TypeError: ('dict.__new__(HTTPHeaderDict): HTTPHeaderDict is not a subtype of dict', <function _reconstructor at 0x03039570>, (<class 'requests.packages.urllib3._collections.HTTPHeaderDict'>, <type 'dict'>, {'date': ('date', 'Thu, 01 Sep 2016 08:24:03 GMT'), 'transfer-encoding': ('transfer-encoding', 'chunked'), 'vary': ('vary', 'Accept'), 'server': ('server', 'gunicorn/19.1.1'), 'x-chembl-retrieval-time': ('x-chembl-retrieval-time', '0.00829792022705'), 'connection': ('connection', 'Keep-Alive'), 'cache-control': ('cache-control', 's-maxage=30000000, max-age=30000000'), 'x-chembl-in-cache': ('x-chembl-in-cache', 'True'), 'content-type': ('content-type', 'application/json')}))

Can you help to solve the problem please ?

All the Best;
Aziz

**Comment by Lukasa** [comment]
This error is coming from requests_cache. I recommend contacting that project for assistance. =)
