### ISSUE TITLE
ValueError: negative shift count in _proxy_bypass_macosx_sysconf

### ISSUE THREAD

**Issue by AndiCui** [kennethreitz/requests#3619]
Pls see https://github.com/pypa/pip/issues/4009

**Comment by Lukasa** [comment]
Sorry you were referred here, but this isn't a requests problem _either_. You should be able to reproduce the problem with this code, which uses entirely modules in the standard library:

``` python
from urllib.request import proxy_bypass
from urllib.parse import urlparse

netloc = urlparse("https://pypi.python.org/pypi").netloc
proxy_bypass(netloc)
```

I should note that I'm a little bit confused here as to why you're encountering this problem with the config you showed in the other post. Is your HTTPS config the same?

**Comment by AndiCui** [comment]
My HTTPS config is absolutely the same.

**Comment by Lukasa** [comment]
Were you able to verify the problem with the standard library code?

**Comment by Lukasa** [comment]
Closing due to inactivity.

**Comment by AndiCui** [comment]
Sorry for the delated answer
I cannot recreate the problem with the lib code, but the network config is changed a bit. (No major changes though)

**Comment by Lukasa** [comment]
@AndiCui So, to be clear, using Requests gives you the problem but using the code above does not.

**Comment by AndiCui** [comment]
I retried once. This time it recreated the issue.
The problem happens when I have a “Location” enabled that is other than the Location which I had that config. 

```
>>> proxy_bypass(netloc)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 2546, in proxy_bypass
    return proxy_bypass_macosx_sysconf(host)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 2523, in proxy_bypass_macosx_sysconf
    return _proxy_bypass_macosx_sysconf(host, proxy_settings)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 2509, in _proxy_bypass_macosx_sysconf
    if (hostIP >> mask) == (base >> mask):
ValueError: negative shift count
```

**Comment by Lukasa** [comment]
So this is not a Requests issue I'm afraid. 😔

**Comment by sigmavirus24** [comment]
To be clear @AndiCui your problem is arising from the standard library, not from within Requests itself. If you're seeing this problem using Requests, we can handle it, but we the ValueError being raised needs to be addressed in the standard library and you should file a bug on bugs.python.org for that.
