### ISSUE TITLE
problem with the proxy

### ISSUE THREAD

**Issue by bifeng** [kennethreitz/requests#3821]
python3 code:
session = requests.session()
r = session.get(url="http://www.google.com",headers=headers,timeout=30,proxies=proxies)
the headers={"User-Agent": random.choice(USER_AGENTS)}
the proxies is like this:
{'http': 'http://117.68.236.155:808', 'https': 'http://117.68.236.155:808'}
I got the following Error Message:
requests.exceptions.ProxyError: HTTPConnectionPool(host='117.68.236.155', port=808): Max retries exceeded with url: http://www.google.com/ (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x0000007C82F8EBE0>: Failed to establish a new connection: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。',)))

Requests verison 2.12.4,  Python3
I have test the following code, but the return is none:
import requests
print(requests.utils.get_environ_proxies('http://www.google.com'))

Is there any solution? I looking forward to your reply!

**Comment by feng-1985** [comment]
import requests
session = requests.session()
r = session.get(url="http://www.google.com")
cookie = session.cookies.get_dict()
print(cookie)

get the following error:
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by Lukasa** [comment]
We appear to be failing to connect to the proxy. Are you sure it is running at 117.68.236.155:808? Can you tell me what Requests version you're using please?

**Comment by sigmavirus24** [comment]
@Lukasa hidden in the original message is:

```
Requests verison 2.12.4, Python3
```

**Comment by sigmavirus24** [comment]
@bifeng in your second example, you're not using proxies. Does this mean that you cannot connect to the internet **at all**?

**Comment by bifeng** [comment]
Yes, I am sure.  The Requests verison is 2.12.4.

**Comment by feng-1985** [comment]
@sigmavirus24 
I am surfing the internet, and run this code , so connect is not the problem.
I am still getting the error:
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
That's weird!

**Comment by feng-1985** [comment]
The complete error message:
Traceback (most recent call last):
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\q\Anaconda3\lib\http\client.py", line 1197, in getresponse
    response.begin()
  File "C:\Users\q\Anaconda3\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\q\Anaconda3\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\q\Anaconda3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\packages\urllib3\util\retry.py", line 334, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 391, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 387, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\q\Anaconda3\lib\http\client.py", line 1197, in getresponse
    response.begin()
  File "C:\Users\q\Anaconda3\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Users\q\Anaconda3\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\q\Anaconda3\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/q/Desktop/review0.2/tmp2.py", line 13, in <module>
    r = session.get(url="http://www.google.com")
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\q\Anaconda3\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by Lukasa** [comment]
So it looks very much like your machine is unable to actually make a network connection to the proxy you're trying to connect to. Without debugging that failure we can't really do much more.
