### ISSUE TITLE
Insert list of data into POST request

### ISSUE THREAD

**Issue by MaxOvcharov** [kennethreitz/requests#3944]
Hi, I try to insert list of data into body of my POST request. Example from documentation: 
```
POST https://apidata.mos.ru/v1/datasets
[ "Id", "Caption", "SefUrl"] 
```
Result:
`[ { "Id": 1147, "Caption": "Электронная нотная библиотека города Москвы", "SefUrl": "7719028495-elektronnaya-notnaya-biblioteka-goroda-moskvy" } ]`

My version of code:
```
import pprint
import requests
from requests import Session, Request

method = 'datasets'
data_list = ["Id", "Caption", "SefUrl"']
s = Session()
req = Request('POST', 'https://apidata.mos.ru/v1/{0}'.format(method))
prepped = req.prepare()
prepped.body = data_list
esponse = s.send(prepped)

response = requests.post('https://apidata.mos.ru/v1/{0}'.format(method), data=data_list)
print response.url

if response.status_code == 200:
    pprint.pprint(response.json())
else:  # TODO - use custom exceptions
    message = "A request to the DataMos API was unsuccessful. The server returned HTTP {0} {1}."
    print message.format(response.status_code, response.reason)
```
The result is:
```
Traceback (most recent call last):
  File "/home/max/bot_project/DataMosAPI/data_mos_api/test_post.py", line 12, in <module>
    response = s.send(prepped)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py", line 356, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 901, in _send_output
    self.send(message_body)
  File "/usr/lib/python2.7/httplib.py", line 873, in send
    self.sock.sendall(data)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 311, in sendall
    sent = self._send_until_done(data[total_sent:total_sent + SSL_WRITE_BLOCKSIZE])
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 301, in _send_until_done
    return self.connection.send(data)
  File "/home/max/bot_project/Bots_Django/venv/local/lib/python2.7/site-packages/OpenSSL/SSL.py", line 1253, in send
    raise TypeError("data must be a memoryview, buffer or byte string")
TypeError: data must be a memoryview, buffer or byte string
```

**Comment by Lukasa** [comment]
It looks like your API is expecting you to post JSON. Try simplifying your code to this:

```python
import pprint
import requests
from requests import Session, Request

method = 'datasets'
data_list = ["Id", "Caption", "SefUrl"']
s = Session()
response = requests.post('https://apidata.mos.ru/v1/{0}'.format(method), json=data_list)
print response.url

if response.status_code == 200:
    pprint.pprint(response.json())
else:  # TODO - use custom exceptions
    message = "A request to the DataMos API was unsuccessful. The server returned HTTP {0} {1}."
    print message.format(response.status_code, response.reason)
```

**Comment by MaxOvcharov** [comment]
It's work. Thank you:)))
