### ISSUE TITLE
when i import requests, UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 1: ordinal not in range(128),how to solve this?

### ISSUE THREAD

**Issue by MyZhang0826** [kennethreitz/requests#3964]
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python2713\lib\site-packages\requests\__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "C:\Python2713\lib\site-packages\requests\packages\urllib3\contrib\pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "C:\Python2713\lib\site-packages\cryptography\x509\__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "C:\Python2713\lib\site-packages\cryptography\x509\base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "C:\Python2713\lib\site-packages\cryptography\x509\extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "C:\Python2713\lib\site-packages\asn1crypto\keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "C:\Python2713\lib\site-packages\asn1crypto\_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "C:\Python2713\lib\site-packages\asn1crypto\_int.py", line 56, in <module>
    from ._perf._big_num_ctypes import libcrypto
  File "C:\Python2713\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py", line 31, in <module>
    libcrypto_path = find_library('crypto')
  File "C:\Python2713\lib\ctypes\util.py", line 53, in find_library
    fname = os.path.join(directory, name)
  File "C:\Python2713\lib\ntpath.py", line 85, in join
    result_path = result_path + p_path
UnicodeDecodeError: 'ascii' codec can't decode byte 0xcf in position 1: ordinal not in range(128)

**Comment by Lukasa** [comment]
Hey there. You have raised this issue before, [here](https://github.com/kennethreitz/requests/issues/1252#issuecomment-291438569), and so I will give the same advice again: this appears to be a problem with asn1crypto, not Requests: please open an issue on their repository.
