### ISSUE TITLE
ModuleNotFoundError: No module named 'email.parser'; 'email' is not a package

### ISSUE THREAD

**Issue by BetterInTime1997** [kennethreitz/requests#3997]
when i run : import requests 
i get the error as following:

~~~shell
D:\python\Python36\python.exe "D:/Python Work Space/test003.py"
Traceback (most recent call last):
  File "D:/Python Work Space/test003.py", line 1, in <module>
    import requests
  File "D:\python\Python36\lib\site-packages\requests\__init__.py", line 60, in <module>
    from .packages.urllib3.exceptions import DependencyWarning
  File "D:\python\Python36\lib\site-packages\requests\packages\__init__.py", line 29, in <module>
    import urllib3
  File "D:\python\Python36\lib\site-packages\urllib3\__init__.py", line 8, in <module>
    from .connectionpool import (
  File "D:\python\Python36\lib\site-packages\urllib3\connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "D:\python\Python36\lib\site-packages\urllib3\exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
  File "D:\python\Python36\lib\site-packages\urllib3\packages\six.py", line 203, in load_module
    mod = mod._resolve()
  File "D:\python\Python36\lib\site-packages\urllib3\packages\six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "D:\python\Python36\lib\site-packages\urllib3\packages\six.py", line 82, in _import_module
    __import__(name)
  File "D:\python\Python36\lib\http\client.py", line 71, in <module>
    import email.parser
ModuleNotFoundError: No module named 'email.parser'; 'email' is not a package
~~~
but i have already installed it
see:

~~~shell
D:\Python Work Space>pip install email
Requirement already satisfied: email in d:\python\python36\lib\site-packages\email-6.0.0a1-py3.6.egg
~~~

**Comment by Lukasa** [comment]
Email is a standard library module that should have come with Python. I *suspect* that `pip install email` made that worse, not better. However, more likely you have a file in the same directory as your code called `email.py`, you need to change that filename.
