### ISSUE TITLE
OpenSSL issue when vendoring requests

### ISSUE THREAD

**Issue by jonathan-ku-reflektion** [kennethreitz/requests#4019]
I was trying to vendor requests in my own library. I used a similar vendoring structure as requests and I put requests under ceslib/packages
However, when I am trying to send a HTTPS request, I see the following error.
It seems like OpenSSL needs to be vendored by requests too?
Code Snippet:
```
import packages.requests as requests
self._session = requests.Session()
req = requests.Request('GET', 'https://www.google.com')
req = self._session.prepare_request(req)
response = self._session.send(req)
```

Error:
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/ceslib/packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/ceslib/packages/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/ceslib/packages/requests/packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/ceslib/packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/ceslib/packages/requests/packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/ceslib/packages/requests/packages/urllib3/connection.py", line 326, in connect
    ssl_context=context)
  File "/usr/lib/python2.7/site-packages/ceslib/packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    context.load_verify_locations(ca_certs, ca_cert_dir)
  File "/usr/lib/python2.7/site-packages/ceslib/packages/requests/packages/urllib3/contrib/pyopenssl.py", line 411, in load_verify_locations
    self._ctx.load_verify_locations(cafile, capath)
  File "/usr/lib/python2.7/site-packages/OpenSSL/SSL.py", line 525, in load_verify_locations
    _raise_current_error()
  File "/usr/lib/python2.7/site-packages/OpenSSL/_util.py", line 48, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('system library', 'fopen', 'No such file or directory'), ('BIO routines', 'BIO_new_file', 'no such file'), ('x509 certificate routines', 'X509_load_cert_crl_file', 'system lib')]```

**Comment by Lukasa** [comment]
Nope, you aren't missing OpenSSL, you're missing the certs bundle `cacerts.pem` in the requests code directory. Looks like you misplaced it in your vendoring.

**Comment by jonathan-ku-reflektion** [comment]
Thank you. Was able to solve this problem by updating the vendored version from 2.13.0 to 2.14.2
