### ISSUE TITLE
Session with cert set can't do HTTP connections

### ISSUE THREAD

**Issue by kaptajnen** [kennethreitz/requests#4025]
It is not clear from the documentation if this is supposed to work, but it did work previously.

If you set the cert attribute on a Session and then make an HTTP request, an AttributeError exception is thrown since `key_file` does not exist on an HTTPConnectionPool object. This behavior was introduced in [this commit](https://github.com/kennethreitz/requests/commit/7d8b87c37f3a5fb993fd83eda6888ac217cd108e#diff-31f6e77c031977d33226530924b4337aR243)

From what I can tell it would continue to work if the certificate was set as a tuple instead, since that would then add the key_file attribute to the HTTPConnectionPool a few lines above.

    >>> import requests
    >>> s = requests.Session()
    >>> s.cert='/path/to/file.pem'
    >>> s.get('http://example.com')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 531, in get
        return self.request('GET', url, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 407, in send
        self.cert_verify(conn, request.url, verify, cert)
      File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 247, in cert_verify
        if conn.key_file and not os.path.exists(conn.key_file):
    AttributeError: 'HTTPConnectionPool' object has no attribute 'key_file'

**Comment by Lukasa** [comment]
Yup, this is definitely a bug. Feel free to take a swing at this if you're interested, otherwise I'll try to fix it tomorrow.

**Comment by kaptajnen** [comment]
I've added a pull request. I'm not familiar with the requests code but I think my simple fix of just not doing anything unless HTTPS is used should work (the tests pass at least).
