### ISSUE TITLE
error after upgrading from 2.14.2 to 2.16.0

### ISSUE THREAD

**Issue by pierrre** [kennethreitz/requests#4075]
(I'm not a Python dev, I don't even know what this project does)

I have an automated Travis CI build that requires `ansible-tower-cli`.
I install it with `pip install --user ansible-tower-cli`.

It began to fail recently:
```
$ tower-cli --help                                                                                                                        
Traceback (most recent call last):
  File "/home/travis/.local/bin/tower-cli", line 90, in <module>
    cli()
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 1018, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 809, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 496, in get_help
    return self.command.get_help(self)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 830, in get_help
    self.format_help(ctx, formatter)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 845, in format_help
    self.format_options(ctx, formatter)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 956, in format_options
    self.format_commands(ctx, formatter)
  File "/home/travis/.local/lib/python2.7/site-packages/click/core.py", line 1000, in format_commands
    for subcommand in self.list_commands(ctx):
  File "/home/travis/.local/bin/tower-cli", line 46, in list_commands
    res = tower_cli.get_resource(filename[:-3])
  File "/home/travis/.local/lib/python2.7/site-packages/tower_cli/__init__.py", line 32, in get_resource
    module = importlib.import_module('tower_cli.resources.%s' % name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/travis/.local/lib/python2.7/site-packages/tower_cli/resources/user.py", line 16, in <module>
    from tower_cli import models
  File "/home/travis/.local/lib/python2.7/site-packages/tower_cli/models/__init__.py", line 20, in <module>
    from tower_cli.models.base import Resource, MonitorableResource, ExeResource, \
  File "/home/travis/.local/lib/python2.7/site-packages/tower_cli/models/base.py", line 36, in <module>
    from tower_cli.api import client
  File "/home/travis/.local/lib/python2.7/site-packages/tower_cli/api.py", line 25, in <module>
    from requests.packages import urllib3
ImportError: No module named packages
```

It looks like this issues is caused by the recent `requests` update.
`ansible-tower-cli` requires `requests>=2.3.0`.
Previously it was installing `2.14.2`, now it's installing `2.16.0`.

If I force the `request` version with `pip install --user requests==2.14.2`
it works.

Is this issue related to all the other recent issue ?

Thanks

**Comment by kennethreitz** [comment]
this is now fixed in the master branch

**Comment by kennethreitz** [comment]
Related: #4073

**Comment by kennethreitz** [comment]
2.16.1 released, which fixes this.

**Comment by pierrre** [comment]
thank you very much for your quick reply ! 👍
