### ISSUE TITLE
Why can't I use decorator with requests?

### ISSUE THREAD

**Issue by marataziat** [kennethreitz/requests#5009]
```
import requests

r = requests

def my_decorator(func):
    def wrapper(*args):
        print(func.hostname)
        print('sdasdas')
    return wrapper

say_wee = my_decorator(r.sessions.urlparse('http://google.com'))
print(type(say_wee))
r.sessions.urlparse = say_wee
r.get('http://google.com')
```
I want to add some actions to the default sessions.urlparse. I get error:
```
Traceback (most recent call last):
  File "res.py", line 14, in <module>
    r.get('http://google.com')
  File "/Library/Python/2.7/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 150, in resolve_redirects
    previous_fragment = urlparse(req.url).fragment
AttributeError: 'NoneType' object has no attribute 'fragment'
```

**Comment by tvytlx** [comment]
Hi, @marataziat 

`say_wee = my_decorator(r.sessions.urlparse('http://google.com'))`

You shouldn't use a decorator on a `ParseResult`.

**Comment by timofurrer** [comment]
What exactly are you trying to achieve? 

Your decorator takes a function as argument, but you actually pass it a `ParseResult`.
And your decorator doesn't call the original `requests.sessions.urlparse`, but you probably want to.

**Comment by ghost** [comment]
@timofurrer I want to add some additional layer of validating to the requests library. I don't want to rewrite all the functions so I made a decorator which just adds some code to the urlparse function.

**Comment by timofurrer** [comment]
If you just want to extend the `r.sessions.urlparse` function your decorator should more look like the following: 

```python
import requests


def my_decorator(func):
    def wrapper(*args, **kwargs):
        print("Got r.sessions.urlparse *args:", args)
        print("Got r.sessions.urlparse **kwargs:", kwargs)
        return func(*args, **kwargs)
    return wrapper


requests.sessions.urlparse = my_decorator(requests.sessions.urlparse)
print(requests.get('http://google.com'))
```

**Comment by ghost** [comment]
Ohhh thank you
